version: "3.9"
services:
  api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/manilla-api:latest
    container_name: manilla-api
    restart: always
    ports:
      - "${PORT_BACKEND:-5000}:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}

  web:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/manilla-web:latest
    container_name: manilla-web
    restart: always
    depends_on:
      - api
    ports:
      - "${PORT_FRONTEND:-3000}:80"

  admin:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/manilla-admin:latest
    container_name: manilla-admin
    restart: always
    depends_on:
      - api
    ports:
      - "${PORT_ADMIN:-3001}:80"
